AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: > 
  items-api
  sam assessment

Globals:
  Function:
    Timeout: 3

Resources:
  EcommerceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Ecommerce
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ItemsApi/create_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EcommerceTable
  ListItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ItemsApi/list_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EcommerceTable

Outputs:
  ItemsApi:
      Description: "API Gateway Items Endpoint Url"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
